server:
  port: 8765

spring:
  application:
    name: saascloud-provider-crm-api
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign.hystrix.enabled: true
